blank_issues_enabled: true
contact_links:
  - name: 💬 Discussion générale
    url: https://discord.com/channels/1399325839665004554/1417133740810833940
    about: Une question, une suggestion, une idée ? Vien sur le serveur Discord !
