services:


  app:
    container_name: dyingstar-webapp
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
    environment:
      - NODE_ENV=development
    env_file:
      - ../.env.local
    tty: true
    networks:
      - backend

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.22
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "6lPJuz9LeW9LKb56DWjeEPso6yh9KEspsFGrpC1dNUM"
      MEILI_ENV: "production"
    volumes:
      - meili_data:/meili_data
    networks:
      - backend

volumes:
  meili_data:

networks:
  backend:
    driver: bridge
