FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production \
    PORT=3000

RUN apk add --no-cache libc6-compat

COPY .next/standalone ./.next/standalone
COPY public ./public
COPY .next/static ./.next/static

RUN addgroup -g 1001 -S nodejs && adduser -S nextjs -u 1001 \
  && chown -R nextjs:nodejs /app
USER nextjs

EXPOSE 3000

CMD ["node", ".next/standalone/server.js"]