services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
    environment:
      - NODE_ENV=development
    env_file:
      - ../.env.local
    tty: true

  valkey:
    image: valkey/valkey:8.1-alpine
    container_name: valkey
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - valkey_data:/data
    command: ["valkey-server", "--appendonly", "yes"]

volumes:
  valkey_data:
