services:
  app:
    image: node:22
    command: >
      sh -c "
        corepack enable &&
        corepack install &&
        pnpm install &&
        pnpm dev
      "
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
    working_dir: /app
    tty: true
    networks:
      - backend

  meilisearch:
    image: getmeili/meilisearch:v1.22
    ports:
      - "7700:7700"
    environment:
      MEILI_ENV: "production"
    volumes:
      - meili_data:/meili_data
    env_file:
      - ../.env.local
    networks:
      - backend

volumes:
  meili_data:

networks:
  backend:
    driver: bridge
