services:
  app:
    container_name: dyingstar-webapp-prod
    image: ${IMAGE}
    restart: unless-stopped
    ports:
      - "8100:3000"
    env_file:
      - /opt/website/envs/prod.env
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 15s
      timeout: 3s
      retries: 5
    tty: true
    networks:
      - backend

  meilisearch:
    container_name: meilisearch-staging
    image: getmeili/meilisearch:v1.22
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "xxxx"
      MEILI_ENV: "production"
    volumes:
      - meili_data:/meili_data
    networks:
      - backend

volumes:
  meili_data:

networks:
  backend:
    driver: bridge
